### ISSUE TITLE
Add ability to refuse passwords that match against bad passwords?

### ISSUE THREAD

**Issue by peterramsing** [ajmueller/express-passport-and-acl#3]
_This might be over-doing it. Sometimes these things are best left out of frameworks and this might be one of them..._

Would it be helpful to offer, out of the box, support to check the password against a sanity check of "bad" passwords like those on lists [like these](https://nakedsecurity.sophos.com/2010/12/15/the-top-50-passwords-you-should-never-use/)?

**Comment by ajmueller** [comment]
I believe the answer I just left in #1 will answer this more thoroughly, but basically I think this is the kind of feature that is best left to individual developers to implement in their own projects if required.  For this feature we would, presumably, store the unsafe passwords in a datastore and need an interface to manage them.  That interface would then be restricted to "super admins" or the equivalent highest level user.

That said, your question brings another question to mind: should we implement additional checks for password strength?  Right now all we have is a minimum password length, but additional requirements could be added to check for a capital letter, a number, a special character, etc.  Of course password strength is a [fun topic](https://xkcd.com/936/) and will lead the discussion down another rabbit hole entirely, but it's a good one to have.  I read an article ages ago comparing password strength meters on various platforms (Dropbox, Twitter, etc.) and how they never really agreed that much.  I did just find a cool one by [Kaspersky](https://password.kaspersky.com/), though, that provides some interesting statistics for each password entered.

**Comment by peterramsing** [comment]
I think, based on #1, that this is not within the scope of this project. _However_, now I want to find a database (or create) one that has a bunch of passwords that shouldn't be used that one could reach out to and check against. Hmmmmmmm.... 💭
